import { jsonb, numeric, pgTable, serial, text } from "drizzle-orm/pg-core";

/**
 * config — Baserow table 224
 * PostgreSQL table: database_table_224
 */
export const config = pgTable("database_table_224", {
  id: serial("id").primaryKey(),
  bodyAuthInstitutionId: text("field_1607"), // body.auth.institutionId (text)
  bodyTenantCompanyName: text("field_1623"), // body.tenant.companyName (text)
  bodyTenantBusinessHours: text("field_1624"), // body.tenant.businessHours (text)
  bodyTenantAddressStreet: text("field_1625"), // body.tenant.address.street (text)
  bodyTenantAddressCity: text("field_1626"), // body.tenant.address.city (text)
  bodyTenantAddressState: text("field_1627"), // body.tenant.address.state (text)
  bodyTenantAddressZipCode: text("field_1628"), // body.tenant.address.zipCode (text)
  bodyAgentSettingsProfileAgentName: text("field_1629"), // body.agentSettings.profile.agentName (text)
  bodyAgentSettingsProfileLanguage: text("field_1630"), // body.agentSettings.profile.language (text)
  bodyAgentSettingsProfilePersonalityDescription: text("field_1631"), // body.agentSettings.profile.personalityDescription (text)
  bodyAgentSettingsProfileExpertiseArea: text("field_1632"), // body.agentSettings.profile.expertiseArea (text)
  bodyAgentSettingsPersonalityGreeting: text("field_1633"), // body.agentSettings.personality.greeting (text)
  bodyAgentSettingsPersonalityClosing: text("field_1634"), // body.agentSettings.personality.closing (text)
  bodyAgentSettingsPersonalityForbiddenWords_0: text("field_1635"), // body.agentSettings.personality.forbiddenWords.0 (text)
  perguntas: text("field_1636"), // perguntas (long_text)
  quanditadePerguntas: text("field_1637"), // quanditadePerguntas (text)
  bodyAgentSettingsStages_0Mission: text("field_1638"), // body.agentSettings.stages.0.mission (text)
  bodyAgentSettingsStages_0Script: text("field_1639"), // body.agentSettings.stages.0.script (text)
  bodyAgentSettingsStages_1Stage: text("field_1640"), // body.agentSettings.stages.1.stage (text)
  bodyAgentSettingsStages_1Agent: text("field_1641"), // body.agentSettings.stages.1.agent (text)
  bodyAgentSettingsStages_1Mission: text("field_1642"), // body.agentSettings.stages.1.mission (text)
  bodyAgentSettingsStages_1Script: text("field_1643"), // body.agentSettings.stages.1.script (text)
  bodyAgentSettingsStages_2Stage: text("field_1644"), // body.agentSettings.stages.2.stage (text)
  bodyAgentSettingsStages_2Agent: text("field_1645"), // body.agentSettings.stages.2.agent (text)
  bodyAgentSettingsStages_2Mission: text("field_1646"), // body.agentSettings.stages.2.mission (text)
  bodyAgentSettingsStages_2Script: text("field_1647"), // body.agentSettings.stages.2.script (text)
  bodyAgentSettingsStages_3Stage: text("field_1648"), // body.agentSettings.stages.3.stage (text)
  bodyAgentSettingsStages_3Agent: text("field_1649"), // body.agentSettings.stages.3.agent (text)
  bodyAgentSettingsStages_3Mission: text("field_1650"), // body.agentSettings.stages.3.mission (text)
  bodyAgentSettingsStages_3Script: text("field_1651"), // body.agentSettings.stages.3.script (text)
  bodyAgentSettingsFlowGreetingsScript: text("field_1652"), // body.agentSettings.flow.greetingsScript (long_text)
  bodyAgentSettingsFlowCompanyOfferings: text("field_1653"), // body.agentSettings.flow.companyOfferings (text)
  bodyAgentSettingsFlowQualificationPrompt: text("field_1654"), // body.agentSettings.flow.qualificationPrompt (text)
  bodyAgentSettingsFlowQualificationFallback: text("field_1655"), // body.agentSettings.flow.qualificationFallback (text)
  bodyAgentSettingsFlowViabilityQuestions_0Prompt: text("field_1656"), // body.agentSettings.flow.viabilityQuestions.0.prompt (text)
  bodyAgentSettingsFlowViabilityQuestions_0Objective: text("field_1657"), // body.agentSettings.flow.viabilityQuestions.0.objective (text)
  bodyAgentSettingsFlowViabilityQuestions_1Prompt: text("field_1658"), // body.agentSettings.flow.viabilityQuestions.1.prompt (text)
  bodyAgentSettingsFlowViabilityQuestions_1Objective: text("field_1659"), // body.agentSettings.flow.viabilityQuestions.1.objective (text)
  bodyAgentSettingsFlowDisqualificationRules: text("field_1660"), // body.agentSettings.flow.disqualificationRules (text)
  bodyAgentSettingsFlowCommitmentType: text("field_1661"), // body.agentSettings.flow.commitmentType (text)
  bodyAgentSettingsFlowCommitmentScript: text("field_1662"), // body.agentSettings.flow.commitmentScript (text)
  bodyAgentSettingsFlowDocumentsChecklist_0: text("field_1663"), // body.agentSettings.flow.documentsChecklist.0 (text)
  bodyAgentSettingsFlowDocumentsChecklist_1: text("field_1664"), // body.agentSettings.flow.documentsChecklist.1 (text)
  bodyAgentSettingsFlowDocumentsChecklist_2: text("field_1665"), // body.agentSettings.flow.documentsChecklist.2 (text)
  bodyAgentSettingsFlowDocumentConfirmationMessage: text("field_1666"), // body.agentSettings.flow.documentConfirmationMessage (text)
  bodyAgentSettingsFlowClosingMessage: text("field_1667"), // body.agentSettings.flow.closingMessage (text)
  bodyAgentSettingsFlowFollowUpRules: text("field_1668"), // body.agentSettings.flow.followUpRules (text)
  wabaPhoneNumber: text("field_1682"), // waba_phone_number (text)
  iaAtivada: text("field_1698"), // ia_ativada (text)
  wabaPhoneId: text("field_1708"), // waba_phone_id (text)
  phoneDepartmentId: numeric("field_1907"), // phone_department_id (number)
  phoneDepartmentName: text("field_1908"), // phone_department_name (text)
  wabaBusinessAccountId: text("field_1927"), // waba_business_account_id (text)
  queueMode: jsonb("field_1975"), // queue_mode (multiple_select)
  riasignWabaConfigId: text("field_2005"), // riasign_waba_config_id (text)
});
