// Auto-generated by scripts/discover-schema.ts
// Do not edit manually — re-run the script to update

export { automation } from "./automation";
export { config } from "./config";
export { cases } from "./cases";
export { caseMessages } from "./caseMessages";
export { webhooks } from "./webhooks";
export { followUpConfig } from "./followUpConfig";
export { followUpHistory } from "./followUpHistory";
export { kanbanColumns } from "./kanbanColumns";
export { caseKanbanStatus } from "./caseKanbanStatus";
export { clients } from "./clients";
export { events } from "./events";
export { eventGuests } from "./eventGuests";
export { users } from "./users";
export { roles } from "./roles";
export { menu } from "./menu";
export { permissions } from "./permissions";
export { rolePermissions } from "./rolePermissions";
export { userRoles } from "./userRoles";
export { auditPermissions } from "./auditPermissions";
export { supportTickets } from "./supportTickets";
export { supportMessages } from "./supportMessages";
export { supportKb } from "./supportKb";
export { calendarSettings } from "./calendarSettings";
export { departments } from "./departments";
export { userDepartments } from "./userDepartments";
export { userFeatures } from "./userFeatures";
export { assignmentQueue } from "./assignmentQueue";
export { lawsuitTracking } from "./lawsuitTracking";
export { lawsuitMovements } from "./lawsuitMovements";
export { pushSubscriptions } from "./pushSubscriptions";
export { pushNotifications } from "./pushNotifications";
export { signEnvelopes } from "./signEnvelopes";
export { documentTemplates } from "./documentTemplates";
