# Stage 1: Dependencies
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copiar arquivos de dependências
COPY package.json package-lock.json* ./
RUN npm ci

# Stage 2: Builder
FROM node:20-alpine AS builder
WORKDIR /app

# Copiar dependências do stage anterior
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Variáveis de ambiente para build
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# NEXT_PUBLIC_* precisam existir no build para serem inlined no client JS
ARG NEXT_PUBLIC_BASEROW_API_URL=https://automation-db.riasistemas.com.br/api
ARG NEXT_PUBLIC_BASEROW_CONFIG_TABLE_ID=224
ARG NEXT_PUBLIC_BASEROW_CASES_TABLE_ID=225
ARG NEXT_PUBLIC_BASEROW_AGENT_STATE_TABLE_ID=226
ARG NEXT_PUBLIC_BASEROW_CASE_MESSAGES_TABLE_ID=227
ARG NEXT_PUBLIC_BASEROW_EVENTS_TABLE_ID=234
ARG NEXT_PUBLIC_BASEROW_EVENT_GUESTS_TABLE_ID=235
ARG NEXT_PUBLIC_BASEROW_USERS_TABLE_ID=236
ARG NEXT_PUBLIC_BASEROW_ROLES_TABLE_ID=237
ARG NEXT_PUBLIC_BASEROW_MENU_TABLE_ID=238
ARG NEXT_PUBLIC_BASEROW_PERMISSIONS_TABLE_ID=239
ARG NEXT_PUBLIC_BASEROW_ROLE_PERMISSION_TABLE_ID=240
ARG NEXT_PUBLIC_BASEROW_USER_ROLE_TABLE_ID=241
ARG NEXT_PUBLIC_BASEROW_AUDIT_PERMISSION_TABLE_ID=242
ARG NEXT_PUBLIC_BASEROW_WEBHOOKS_TABLE_ID=228
ARG NEXT_PUBLIC_BASEROW_FOLLOW_UP_CONFIG_TABLE_ID=229
ARG NEXT_PUBLIC_BASEROW_FOLLOW_UP_HISTORY_TABLE_ID=230
ARG NEXT_PUBLIC_BASEROW_DEPARTMENTS_TABLE_ID=247
ARG NEXT_PUBLIC_BASEROW_USER_DEPARTMENTS_TABLE_ID=248
ARG NEXT_PUBLIC_BASEROW_KANBAN_COLUMNS_TABLE_ID=231
ARG NEXT_PUBLIC_BASEROW_CASE_KANBAN_STATUS_TABLE_ID=232
ARG NEXT_PUBLIC_ONBOARDING_API_URL=/api/onboarding
ARG NEXT_PUBLIC_CHAT_POLL_INTERVAL_MS=10000
ARG NEXT_PUBLIC_WHATSAPP_CLIENT_ID=1990068605120799
ARG NEXT_PUBLIC_WHATSAPP_REDIRECT_URI=https://automation-webhook.riasistemas.com.br/webhook/wa/auth
ARG NEXT_PUBLIC_WHATSAPP_CONFIG_ID=1339029904935343
ARG NEXT_PUBLIC_VAPID_PUBLIC_KEY=BH1YQiNZCrXNA0TmA1HT1woAKtAGpi5XkPinUd59VAH1Fp5_DIdpZV6p_nwAmzNzgz8oaYQhxxMB6cwhmLLdl0c

ENV NEXT_PUBLIC_BASEROW_API_URL=$NEXT_PUBLIC_BASEROW_API_URL
ENV NEXT_PUBLIC_BASEROW_CONFIG_TABLE_ID=$NEXT_PUBLIC_BASEROW_CONFIG_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_CASES_TABLE_ID=$NEXT_PUBLIC_BASEROW_CASES_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_AGENT_STATE_TABLE_ID=$NEXT_PUBLIC_BASEROW_AGENT_STATE_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_CASE_MESSAGES_TABLE_ID=$NEXT_PUBLIC_BASEROW_CASE_MESSAGES_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_EVENTS_TABLE_ID=$NEXT_PUBLIC_BASEROW_EVENTS_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_EVENT_GUESTS_TABLE_ID=$NEXT_PUBLIC_BASEROW_EVENT_GUESTS_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_USERS_TABLE_ID=$NEXT_PUBLIC_BASEROW_USERS_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_ROLES_TABLE_ID=$NEXT_PUBLIC_BASEROW_ROLES_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_MENU_TABLE_ID=$NEXT_PUBLIC_BASEROW_MENU_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_PERMISSIONS_TABLE_ID=$NEXT_PUBLIC_BASEROW_PERMISSIONS_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_ROLE_PERMISSION_TABLE_ID=$NEXT_PUBLIC_BASEROW_ROLE_PERMISSION_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_USER_ROLE_TABLE_ID=$NEXT_PUBLIC_BASEROW_USER_ROLE_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_AUDIT_PERMISSION_TABLE_ID=$NEXT_PUBLIC_BASEROW_AUDIT_PERMISSION_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_WEBHOOKS_TABLE_ID=$NEXT_PUBLIC_BASEROW_WEBHOOKS_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_FOLLOW_UP_CONFIG_TABLE_ID=$NEXT_PUBLIC_BASEROW_FOLLOW_UP_CONFIG_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_FOLLOW_UP_HISTORY_TABLE_ID=$NEXT_PUBLIC_BASEROW_FOLLOW_UP_HISTORY_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_DEPARTMENTS_TABLE_ID=$NEXT_PUBLIC_BASEROW_DEPARTMENTS_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_USER_DEPARTMENTS_TABLE_ID=$NEXT_PUBLIC_BASEROW_USER_DEPARTMENTS_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_KANBAN_COLUMNS_TABLE_ID=$NEXT_PUBLIC_BASEROW_KANBAN_COLUMNS_TABLE_ID
ENV NEXT_PUBLIC_BASEROW_CASE_KANBAN_STATUS_TABLE_ID=$NEXT_PUBLIC_BASEROW_CASE_KANBAN_STATUS_TABLE_ID
ENV NEXT_PUBLIC_ONBOARDING_API_URL=$NEXT_PUBLIC_ONBOARDING_API_URL
ENV NEXT_PUBLIC_CHAT_POLL_INTERVAL_MS=$NEXT_PUBLIC_CHAT_POLL_INTERVAL_MS
ENV NEXT_PUBLIC_WHATSAPP_CLIENT_ID=$NEXT_PUBLIC_WHATSAPP_CLIENT_ID
ENV NEXT_PUBLIC_WHATSAPP_REDIRECT_URI=$NEXT_PUBLIC_WHATSAPP_REDIRECT_URI
ENV NEXT_PUBLIC_WHATSAPP_CONFIG_ID=$NEXT_PUBLIC_WHATSAPP_CONFIG_ID
ENV NEXT_PUBLIC_VAPID_PUBLIC_KEY=$NEXT_PUBLIC_VAPID_PUBLIC_KEY

# Cache-bust: incrementar quando NEXT_PUBLIC_* mudar para invalidar build cache
# v2: added NEXT_PUBLIC_VAPID_PUBLIC_KEY
LABEL build.cache.version="2"

# Build da aplicação
RUN npm run build

# Stage 3: Runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# FFmpeg para conversão de áudio para OGG/OPUS (formato WhatsApp)
RUN apk add --no-cache ffmpeg

# Criar usuário não-root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copiar arquivos necessários
COPY --from=builder /app/public ./public

# Verificar se o standalone existe antes de copiar
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Verificar se server.js existe
RUN test -f server.js || (echo "ERRO: server.js não encontrado!" && exit 1)

# Ajustar permissões
RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Healthcheck básico
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD node -e "require('http').get('http://localhost:3000/api/health', (r) => {let data='';r.on('data',(c)=>{data+=c});r.on('end',()=>{try{const json=JSON.parse(data);process.exit(json.status==='ok'?0:1)}catch(e){process.exit(r.statusCode===200?0:1)}})}).on('error',()=>process.exit(1))"

CMD ["node", "server.js"]

