version: "3.8"

services:
  onboarding-app:
    image: onboarding-app:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      # Removido placement constraints para teste
      # placement:
      #   constraints:
      #     - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=minha_rede"
        - "traefik.http.routers.onboarding-app.rule=Host(`onboarding.example.com`)"
        - "traefik.http.routers.onboarding-app.entrypoints=websecure"
        - "traefik.http.routers.onboarding-app.tls.certresolver=letsencrypt"
        - "traefik.http.routers.onboarding-app.service=onboarding-app"
        - "traefik.http.services.onboarding-app.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_ONBOARDING_API_URL=/api/onboarding
      - NEXT_PUBLIC_LOGIN_WEBHOOK_URL=${NEXT_PUBLIC_LOGIN_WEBHOOK_URL}
    networks:
      - minha_rede
    volumes:
      - onboarding-uploads:/app/public/rag-uploads
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {let data='';r.on('data',(c)=>{data+=c});r.on('end',()=>{try{const json=JSON.parse(data);process.exit(json.status==='ok'?0:1)}catch(e){process.exit(r.statusCode===200?0:1)}})}).on('error',()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  onboarding-uploads:
    driver: local

networks:
  minha_rede:
    external: true

